### ISSUE TITLE
Upon resuming the keychain occasionally throws exceptions when getting.

### ISSUE THREAD

**Issue by ggozad** [shazron/KeychainPlugin#20]
After using the app to set/get keys and if the app sleeps and resumes, on occasion (perhaps after opening other memory-heavy apps in between) the keychain throws on get:

``The operation couldn’t be completed. (SFHFKeychainUtilsErrorDomain error -34018.)``

Re-trying does not seem to work, only killing and restarting the app does.

**Comment by ranjitpandit** [comment]
I'm seeing the same problem but it happens when my app does a window.reload()

I'm using ionic, angular, phonegap and this keychain plugin.
com.shazron.cordova.plugin.keychainutil 2.0.0 "KeyChain Plugin for Cordova iOS"

We are unable to release the app due to this issue. Could you please look into this.

Here are some logs.
2015-07-03 16:49:13.690 Moica-Dev1[4482:624229] appUpdateView: restarting app
2015-07-03 16:49:13.691 Moica-Dev1[4482:624229] setting location to home page
2015-07-03 16:49:13.692 Moica-Dev1[4482:624229] resetting application
2015-07-03 16:49:13.706 Moica-Dev1[4482:624229] Resetting plugins due to page load.
2015-07-03 16:49:14.566 Moica-Dev1[4482:624229] THREAD WARNING: ['Keychain'] took '22.825195' ms. Plugin should use a background thread.
2015-07-03 16:49:14.567 Moica-Dev1[4482:624229] error reading credentials from keyChain : error retrieving value for key 'credentials' : The operation couldn’t be completed. (SFHFKeychainUtilsErrorDomain error -34018.)

**Comment by ranjitpandit** [comment]
What could be causing this issue? Is "resettings plugins" the problem?
Is there a work around?

**Comment by softBarbarian** [comment]
@ggozad i am experiencing same problem. Did you ever figure out the fix?

**Comment by softBarbarian** [comment]
also i am thinking about using this plugin: https://github.com/Crypho/cordova-plugin-secure-storage

**Comment by softBarbarian** [comment]
...crickets...

**Comment by shazron** [comment]
I'm hardly maintaining this plugin as is -- no time. If others want to have access or even take this over, let me know.

**Comment by softBarbarian** [comment]
@zhazron I would love to maintain it, but I do not have enough Objective-C experience. However there is another popular fork of your plugin that is maintained by @EddyVerbruggen and I was wondering if @EddyVerbruggen can take this plugin over?

**Comment by shazron** [comment]
Would love for @EddyVerbruggen to take this over ;)

**Comment by EddyVerbruggen** [comment]
Hey @softBarbarian @shazron ok ok, I volunteer ;)

I'll report back here once I'm ready for it, need to discuss a few things first.

**Comment by softBarbarian** [comment]
@EddyVerbruggen great to hear that. I might be able to help out whit what I can.

**Comment by ggozad** [comment]
Departing from KeychainPlugin we went forward fixed bugs and added android support as well as browser for tests in https://github.com/Crypho/cordova-plugin-secure-storage . I am happy to contribute as well, but not certain what it means in terms of proliferation of plugins that do the same thing.
Let me know in any case, I am the author of the plugin.

**Comment by shazron** [comment]
It doesn't matter to me what happens to this repo. Since there has been divergence, I strongly hope all the forks would gather forces and work within one repo, wherever it is, for the benefit of all.

**Comment by jacquesdev** [comment]
@EddyVerbruggen, not sure if you did ever take this over, but perhaps @mlynch from driftyco can take the lead on this?

**Comment by mlynch** [comment]
Happy to do whatever. I would love some feedback on my fork to see if it helps anyone. The underlying keychain library abstraction was changed out which might fix some of these issues incidentally:

https://github.com/driftyco/cordova-plugin-ios-keychain

**Comment by shazron** [comment]
The end of the line. Filed #36

**Comment by shazron** [comment]
See updated README: https://github.com/shazron/KeychainPlugin/blob/master/README.md
